apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: VerrazzanoFleet
metadata:
  name: metallb
spec:
  clusterSelector:
    matchLabels:
      MetalLBChart: enabled
  repoURL: https://metallb.github.io/metallb
  chartName: metallb
  releaseName: metallb
