apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: VerrazzanoFleet
metadata:
  name: mysql-operator
spec:
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  namespace: mysql
  clusterSelector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: manoj
  repoURL: https://mysql.github.io/mysql-operator/
  chartName: mysql-operator
