apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: VerrazzanoFleet
metadata:
  name: pg
spec:
  clusterSelector:
    matchLabels:
      postgresChart: enabled
  version: 5.3.1
  namespace: default
  repoURL: oci://registry.developers.crunchydata.com/crunchydata
  chartName: pgo
